language: node_js
node_js:
  - 13

services:
  - docker

# Scripts to be run such as tests
before_script:
  - echo "no tests"

before_install:

    - docker -v && docker-compose -v
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - sudo mv ./kubectl /usr/local/bin/kubectl

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

script:
  - docker --version # print the version for logging

  - docker build -t udagram-api-feed 
  - docker tag udagram-api-feed echobrook/udagram-api-feed:latest

  - docker build -t udagram-frontend 
  - docker tag udagram-frontend echobrook/udagram-frontend:latest

  - docker build -t udagram-api-user 
  - docker tag udagram-api-user echobrook/udagram-api-user:latest
  
  - docker build -t udagram-reverseproxy 
  - docker tag udagram-reverseproxy echobrook/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push echobrook/udagram-api-feed
  - docker push echobrook/udagram-frontend
  - docker push echobrook/udagram-api-user
  - docker push echobrook/udagram-reverseproxy