branches:
  except:
  - monolith-to-microservices
  only:
  - master

language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"
  
# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  - docker build -t udagram-api-user -f udagram-api-user/Dockerfile udagram-api-user/
  - docker tag udagram-api-user echobrook/udagram-api-user:latest
  
  - docker build -t udagram-api-feed -f udagram-api-feed/Dockerfile udagram-api-feed/
  - docker tag udagram-api-feed echobrook/udagram-api-feed:latest

  - docker build -t udagram-frontend -f udagram-frontend/Dockerfile udagram-frontend/
  - docker tag udagram-frontend echobrook/udagram-frontend:latest

  - docker build -t udagram-reverseproxy -f udagram-reverseproxy/Dockerfile udagram-reverseproxy/
  - docker tag udagram-reverseproxy echobrook/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push echobrook/udagram-api-feed
  - docker push echobrook/udagram-api-user
  - docker push echobrook/udagram-frontend
  - docker push echobrook/udagram-reverseproxy